# Default values for methode-image-set-mapper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 1
image:
  repository: coco/methode-image-set-mapper
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 512Mi
  limits:
    memory: 1.5Gi


